# -*- coding: utf-8 -*-
"""Day10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbVgweGoZpWpL_ogHfMpBsbJDcD912ZC
"""

with open("notes.txt", "r") as file:
  content = file.read()
  print(content)

with open("notes.txt", "w") as file:
  file.write("\nThis is a new note.\n")

with open("notes1.txt", "a") as file:
  file.write("\nThis is a new second note.")



# Step 2: Display menu options
def show_menu():
  print("\n--- Note-Taking App Menu ---")
  print("1. Add a new note")
  print("2. View all notes")
  print("3. Delete all notes")
  print("4. Exit")

# Step 3: Add a new note
def add_note():
  note = input("Enter your note: ")
  with open(FILE_NAME, "a") as file:
    file.write(note + "\n")
  print("Note added successfully!")

# Step 4: View all notes
def view_notes():
  try:
    with open(FILE_NAME, "r") as file:
      content = file.read()
      if content:
       
