# -*- coding: utf-8 -*-
"""Day7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TPB2UzPad2QwAgJzDIeCIOdSbELIXwoE
"""

# shopping_list = ["Milk", "Eggs", "Bread"]
# #print(shopping_list[1])

# shopping_list.append("Butter")
# shopping_list.insert(1, "Juice")

# print(shopping_list)

# shopping_list.sort()
# print(shopping_list)

# shopping_list.reverse()

# print(shopping_list)

# shopping_list.clear()
# print(shopping_list)

# # shopping_list.remove("Bread")
# # print(shopping_list)

# # shopping_list.pop(0)
# # print(shopping_list)

# # for item in shopping_list:
# #     print(f"- {item}")

# # for index, item in enumerate(shopping_list):
# #     print(f"{index + 1}. {item}")

# Shopping List App

# Step 1: Initialize an empty shopping list
shopping_list = []

# Step 2: Define the main menu
def show_menu():
  print("\n--- Shopping List Menu ---")
  print("1. View the shopping list")
  print("2. Add an item")
  print("3. Remove an item")
  print("4. Clear List")
  print("5. Exit")

# Step 3: Main Program Loop

  
