# -*- coding: utf-8 -*-
"""Day8.ipynb

Automatically generated by Colab.


contact = {
    "name": "John Doe",
    "phone": "123-456-7890",
    "email": "john@example.com"
}

# print(contact.get("email"))

contact["phone"] = "980-123-4563"

# print(contact)

contact["address"] = "123 Main St"

# print(contact)

# del contact["email"]

print(contact)

for key, value in contact.items():
    print(f"{key}: {value}")

if "email" in contact:
    print("Email found!")
else:
    print("Email not found.")

from os import name
# Contact Book

# Step 1: Initialize an empty contact book
contacts = {}

# Step 2: Display the menu
def show_menu():
  print("\n--- Contact Book Menu ---")
  print("1. Add Contact")
  print("2. View Contacts")
  print("3. Search Contact")
  print("4. Edit Contact")
  print("5. Delete Contact")
  print("6. Exit")

# Step 3: Add a Contact
def add_contact():
  name = input("Enter contact name: ")
  phone = input("Enter contact number: ")
  email = input("Enter contact email: ")
  contacts[name] = {"phone": phone, "email": email}
  print(f"Contact {name} has been added to your contact book successfully!")

# Step 4: View All Contacts
def view_contacts():
  if contacts:
    print("\n--- Contact List ---")
    for name, details in contacts.items():
      print(f"Name: {name}")
      print(f"Phone: {details['phone']}")
      print(f"Email: {details['email']}")
  else:
    print("Your contact book is empty.")

# Step 5: Search a Contact
def search_contact():
  name = input("Enter the name of the contact you want to search: ")
  if name in contacts:

# Step 6: Edit a contact
def edit_contact():
  name = input("Enter the name of the contact you want to edit: ")
  if name in contacts:
    phone = input("Enter new phone number: ")
    email = input("Enter new email: ")


