# -*- coding: utf-8 -*-
"""Day9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yA12SeDiyYXc6E6vDFHvS7BcMW3FiSV7
"""

# my_tuple = (1, 2, 3)


# print(fruits[0])

# print(fruits[-1])

coordinates = (10, 20, 30)
x, y, z = coordinates
# print(x)
# print(y)
# print(z)

fruits = ("apple", "banana", "cherry")
print(len(fruits))


print(fruits + ("orange",))

my_set = {1, 2, 3}

ingredients = {"flour", "sugar", "butter"}
print(ingredients)

ingredients.add("eggs")

ingredients.remove("sugar")
print(ingredients)

set_a = {"flour", "sugar", "butter"}
set_b = {"sugar", "eggs"}

print(set_a | set_b)
print(set_a & set_b)
print(set_a - set_b)

# Ingredients Checker

# Step 1: Define the recipe ingredients

